### ISSUE TITLE
Encountered error during discovery - since Generac API Update

### ISSUE THREAD

**Issue by monteroman** [drudge/homebridge-mobilelink#5]
**Describe The Bug:**
Since the app got updated last weekend, the plugin for Homebridge throws this error that MobileLink encountered an error during discovery.

**To Reproduce:**
It happens every few minutes or so or when HB is restarted.

**Expected behavior:**

**Logs:**

```
[MobileLink] Encountered error during discovery: RequestError: getaddrinfo ENOTFOUND api.mobilelinkgen.com
    at ClientRequest.<anonymous> (/homebridge/node_modules/homebridge-mobilelink/node_modules/got/dist/source/core/index.js:953:111)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:327:22)
    at ClientRequest.origin.emit (/homebridge/node_modules/homebridge-mobilelink/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
    "authToken": "***************************",
    "discoverFrequency": 60000,
    "platform": "MobileLink"

**Screenshots:**
n/a

**Environment:**

* **Plugin Version**: V0.3.2
* **Homebridge Version**: V1.3.4
* **Node.js Version**:  V14.16
* **NPM Version**: V6.14.11
* **Operating System**: Ubuntu 18.04.5 LTS

<!-- Click the "Preview" tab before you submit to ensure the formatting is correct. -->

**Comment by drudge** [comment]
Generac has removed the old API and the new one is quite a bit different. I'm working on reverse engineering the new API and will update the plugin once I fully understand the changes.

**Comment by drudge** [comment]
Version 2.1 has been released and works with the latest Mobile Link. The switch will be On when the generator is running and Off when it is not.
